language: objective-c
osx_image: xcode7.3

branches:
  only:
  - py3-qtpy-pyside2

script:
- python3 buildPy2app.py py2app

before_install:
- hg clone https://alby128@bitbucket.org/alby128/py2app
- brew update
- brew upgrade python
- which python3
- python3 --version
- which pip3
- pip3 --version
- curl -O http://syncplay.s3.amazonaws.com/qt595.rb
- mv qt595.rb qt.rb
- brew install ./qt.rb
- curl -L https://bintray.com/alby128/Syncplay/download_file?file_path=PySide2-5.9.0a1-5.9.5-cp36-cp36m-macosx_10_11_x86_64.whl -o PySide2-5.9.0a1-5.9.5-cp36-cp36m-macosx_10_11_x86_64.whl
- pip3 install PySide2-5.9.0a1-5.9.5-cp36-cp36m-macosx_10_11_x86_64.whl
- ln -s /usr/local/lib/python3.6/site-packages/PySide2/libpyside2.cpython-36m-darwin.5.9.dylib /usr/local/lib/
- ln -s /usr/local/lib/python3.6/site-packages/PySide2/libshiboken2.cpython-36m-darwin.5.9.dylib /usr/local/lib/
#- python -c "from PySide2 import QtCore"
- python3 -c "from PySide2.QtCore import __version__; print(__version__)" 
- cd py2app
- python3 setup.py install
- cd ..
- python3 -c "from py2app.recipes import pyside2" 

install:
- pip3 install twisted appnope
- pip3 install -U https://github.com/requests/requests/zipball/master


before_deploy:
- pip3 install dmgbuild
- mkdir dist_dmg
- mv resources/macos_vlc_install.command resources/.macos_vlc_install.command
- mv resources/lua/intf/syncplay.lua resources/lua/intf/.syncplay.lua
- mv resources/macOS_readme.pdf resources/.macOS_readme.pdf
- export VER="$(cat syncplay/__init__.py | awk '/version/ {gsub("\047", "", $3); print $NF}')"
- dmgbuild -s appdmg.py "Syncplay" dist_dmg/Syncplay_${VER}_macOS_py36.dmg

deploy:
  skip_cleanup: true
  on: py3-qtpy-pyside2
  provider: bintray
  file: "bintray.json"
  user: alby128
  key:
    secure: "N4XK9IxGEj+5aMskTEvUWwXSMXtHDFcjiLvnPRzVT3OOTSAA2AYjlH975MGiGEanap5gq5ftIo+M2TVNfiqflE9GSlFir+KfzabheoONZVegAq2sG6rDq9YElGJ8JefEb2O8vZykeyvow6TBxcsFdbV44RbGmf4obLALXKgK1cXG8MCKj8VOxVZpgaXFnNCxVlN1AlORx6MQ4ukaZMuO7fDnHjAgnkGlZOBq7/kMJfYGdZvLkKoe6qEoZHJQxVTcA3pkIwRQci5kx/AAxCuKcXYLpoHot5dytIumk0iwfzDqN4uUX5qOG8o2FrWy+7z/Yt7W97lA5c6hVltsoX5dqp0WB14EKgYq+wQwSNcI6tInjogDo4JnGSu1Tpmsy+Fc3Y5Z1cD29hWimxcC8h/wlm9C2hOjfEsdLOfkghevMjRdAW2RIIA8/KmR1Xi2EX78Q75wrPHvo4/4x0Cw0ZviN2wC9LY3GU8tmGjjC0P+WsF4M1Y9by2H2xLHuYPB7h7OnlD67d8pPQVq84Yl2jq9kT2PoYjlNwqWz1r/PsLBCGlXQtlTc7FQKXUAREFwBJY+b5mk2xMsiZZsNrtIfRQ2roDbHws+M0mAQPo1eqeDKLPH8fkDf/ZhWzE+swLadoGxuwKSux53ySAp7CQeObJYWJ3eHfO0cI21DZmd9uyjayA="